services:
  - type: web
    name: asu-rag-api
    env: python
    plan: free
    buildCommand: pip install -r requirements-prod.txt
    startCommand: gunicorn --bind 0.0.0.0:$PORT scripts.start_production:main
    healthCheckPath: /health
    envVars:
      - key: OPENAI_API_KEY
        sync: false
      - key: TWILIO_ACCOUNT_SID
        sync: false
      - key: TWILIO_AUTH_TOKEN
        sync: false
      - key: TWILIO_PHONE_NUMBER
        sync: false
      - key: QDRANT_URL
        value: "http://localhost:6333"
      - key: QDRANT_API_KEY
        sync: false
      - key: FLASK_ENV
        value: "production"
      - key: PYTHONPATH
        value: "." 